// <auto-generated />
using System;
using AppData.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppData.Migrations
{
    [DbContext(typeof(exam_distribution_testContext))]
    [Migration("20240823093038_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppData.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("created_date");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("AppData.Models.DepartmentFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("IdDepartment")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_department");

                    b.Property<Guid?>("IdFacility")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_facility");

                    b.Property<Guid?>("IdStaff")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_staff");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_date");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartment");

                    b.HasIndex("IdFacility");

                    b.HasIndex("IdStaff");

                    b.ToTable("department_facility", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("created_date");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("facility", (string)null);
                });

            modelBuilder.Entity("AppData.Models.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("created_date");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("major", (string)null);
                });

            modelBuilder.Entity("AppData.Models.MajorFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("IdDepartmentFacility")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_department_facility");

                    b.Property<Guid?>("IdMajor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_major");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_date");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartmentFacility");

                    b.HasIndex("IdMajor");

                    b.ToTable("major_facility", (string)null);
                });

            modelBuilder.Entity("AppData.Models.staff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountFe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("account_fe");

                    b.Property<string>("AccountFpt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("account_fpt");

                    b.Property<long?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("created_date");

                    b.Property<long?>("LastModifiedDate")
                        .IsRequired()
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("staff_code");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("AppData.Models.StaffMajorFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<long?>("CreatedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("created_date");

                    b.Property<Guid?>("IdMajorFacility")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_major_facility");

                    b.Property<Guid?>("IdStaff")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_staff");

                    b.Property<long?>("LastModifiedDate")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_date");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("IdMajorFacility");

                    b.HasIndex("IdStaff");

                    b.ToTable("staff_major_facility", (string)null);
                });

            modelBuilder.Entity("AppData.Models.DepartmentFacility", b =>
                {
                    b.HasOne("AppData.Models.Department", "IdDepartmentNavigation")
                        .WithMany("DepartmentFacilities")
                        .HasForeignKey("IdDepartment")
                        .HasConstraintName("FK__departmen__id_de__2A4B4B5E");

                    b.HasOne("AppData.Models.Facility", "IdFacilityNavigation")
                        .WithMany("DepartmentFacilities")
                        .HasForeignKey("IdFacility")
                        .HasConstraintName("FK__departmen__id_fa__2B3F6F97");

                    b.HasOne("AppData.Models.staff", "IdStaffNavigation")
                        .WithMany("DepartmentFacilities")
                        .HasForeignKey("IdStaff")
                        .HasConstraintName("FK__departmen__id_st__2C3393D0");

                    b.Navigation("IdDepartmentNavigation");

                    b.Navigation("IdFacilityNavigation");

                    b.Navigation("IdStaffNavigation");
                });

            modelBuilder.Entity("AppData.Models.MajorFacility", b =>
                {
                    b.HasOne("AppData.Models.DepartmentFacility", "IdDepartmentFacilityNavigation")
                        .WithMany("MajorFacilities")
                        .HasForeignKey("IdDepartmentFacility")
                        .HasConstraintName("FK__major_fac__id_de__30F848ED");

                    b.HasOne("AppData.Models.Major", "IdMajorNavigation")
                        .WithMany("MajorFacilities")
                        .HasForeignKey("IdMajor")
                        .HasConstraintName("FK__major_fac__id_ma__31EC6D26");

                    b.Navigation("IdDepartmentFacilityNavigation");

                    b.Navigation("IdMajorNavigation");
                });

            modelBuilder.Entity("AppData.Models.StaffMajorFacility", b =>
                {
                    b.HasOne("AppData.Models.MajorFacility", "IdMajorFacilityNavigation")
                        .WithMany("StaffMajorFacilities")
                        .HasForeignKey("IdMajorFacility")
                        .HasConstraintName("FK__staff_maj__id_ma__34C8D9D1");

                    b.HasOne("AppData.Models.staff", "IdStaffNavigation")
                        .WithMany("StaffMajorFacilities")
                        .HasForeignKey("IdStaff")
                        .HasConstraintName("FK__staff_maj__id_st__35BCFE0A");

                    b.Navigation("IdMajorFacilityNavigation");

                    b.Navigation("IdStaffNavigation");
                });

            modelBuilder.Entity("AppData.Models.Department", b =>
                {
                    b.Navigation("DepartmentFacilities");
                });

            modelBuilder.Entity("AppData.Models.DepartmentFacility", b =>
                {
                    b.Navigation("MajorFacilities");
                });

            modelBuilder.Entity("AppData.Models.Facility", b =>
                {
                    b.Navigation("DepartmentFacilities");
                });

            modelBuilder.Entity("AppData.Models.Major", b =>
                {
                    b.Navigation("MajorFacilities");
                });

            modelBuilder.Entity("AppData.Models.MajorFacility", b =>
                {
                    b.Navigation("StaffMajorFacilities");
                });

            modelBuilder.Entity("AppData.Models.staff", b =>
                {
                    b.Navigation("DepartmentFacilities");

                    b.Navigation("StaffMajorFacilities");
                });
#pragma warning restore 612, 618
        }
    }
}
